### ISSUE TITLE
Add some examples?

### ISSUE THREAD

**Issue by Naereen** [danmacnish/cartoonify#6]
Hi!
This project sounds awesome!
But so far it's kinda hard to know what it does on an input image and what does the result look like.
Could you try to include some examples please? Like two or three input/output examples?
Thanks.

**Comment by durvesh00755** [comment]
Yes, examples would be of great help to understand this project before performing it.

**Comment by justswim** [comment]
I hacked together a demo of just the image processing part. Check it out here: https://www.kapwing.com/cartoonify

**Comment by Naereen** [comment]
Very impressive :clap: ! A link to this demo should be added to the README.md of this project!

**Comment by danmacnish** [comment]
Thanks Eric! This is fantastic. I've just added it to the readme.

**Comment by Naereen** [comment]
Closing this, but #9 also asks an important question.

**Comment by shoutOutYangJie** [comment]
> I hacked together a demo of just the image processing part. Check it out here: https://www.kapwing.com/cartoonify

Can you tell me what the method is? Which code is important?
